### PR TITLE
Switch Semistandard and fix lint errors

### PR DESCRIPTION
**Pull request by Flet**
@ecaron

### CODE REVIEW

**Comment by Flet** [comment]
added another commit to fix up the tests that had invalid SKUs. This should work for now, but we may want to consider a more reliable approach.

**Comment by ecaron** [comment]
@Flet, I'm thinking to wait to merge this until the Travis builds pass. Agreed?

**Comment by Flet** [comment]
Yeah. There is a strange certificate error happening that is making it fail now. Checking it out.

**Comment by Flet** [comment]
🎉 🎉 🎉

**Pull request merged**
